"""initial_schema_all_tables

Revision ID: e487e1a1e252
Revises:
Create Date: 2026-09-12 12:30:47.457879

"""
from typing import Sequence, Union

from alembic import op  # type: ignore
import sqlalchemy as sa  # type: ignore
from sqlalchemy.dialects import postgresql  # type: ignore

# revision identifiers, used by Alembic.
revision: str = 'e487e1a1e252'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('category_department_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_department_mappings_category_id'), 'category_department_mappings', ['category_id'], unique=False)
    op.create_index(op.f('ix_category_department_mappings_department_id'), 'category_department_mappings', ['department_id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('head_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('radius', sa.Float(), nullable=True),
    sa.Column('complaint_count', sa.Integer(), nullable=False),
    sa.Column('severity_score', sa.Float(), nullable=True),
    sa.Column('urgency_level', sa.String(length=20), nullable=True),
    sa.Column('priority_score', sa.SmallInteger(), nullable=True),
    sa.Column('affected_population', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('first_reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_incidents_category', 'incidents', ['category'], unique=False)
    op.create_index('ix_incidents_location', 'incidents', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_index('ix_incidents_status_priority', 'incidents', ['status', 'priority_score'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index('ix_users_role_active', 'users', ['role', 'is_active'], unique=False)
    op.create_table('complaints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('complaint_number', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('normalized_text', sa.Text(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('category_confidence', sa.Float(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('department_confidence', sa.Float(), nullable=True),
    sa.Column('severity_score', sa.Float(), nullable=True),
    sa.Column('severity_level', sa.String(length=20), nullable=True),
    sa.Column('severity_confidence', sa.Float(), nullable=True),
    sa.Column('urgency_level', sa.String(length=20), nullable=True),
    sa.Column('urgency_confidence', sa.Float(), nullable=True),
    sa.Column('priority_level', sa.String(length=5), nullable=True),
    sa.Column('priority_score', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_text', sa.String(length=500), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('affected_population_estimate', sa.String(length=20), nullable=True),
    sa.Column('vulnerable_population_flag', sa.Boolean(), nullable=False),
    sa.Column('essential_service_flag', sa.Boolean(), nullable=False),
    sa.Column('safety_risk_flag', sa.Boolean(), nullable=False),
    sa.Column('duration_hours', sa.Float(), nullable=True),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('predicted_resolution_hours', sa.Float(), nullable=True),
    sa.Column('prediction_confidence', sa.Float(), nullable=True),
    sa.Column('assigned_officer_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_officer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_complaints_category', 'complaints', ['category_id'], unique=False)
    op.create_index(op.f('ix_complaints_complaint_number'), 'complaints', ['complaint_number'], unique=True)
    op.create_index('ix_complaints_created_at', 'complaints', ['created_at'], unique=False)
    op.create_index('ix_complaints_department', 'complaints', ['department_id'], unique=False)
    op.create_index(op.f('ix_complaints_incident_id'), 'complaints', ['incident_id'], unique=False)
    op.create_index('ix_complaints_location', 'complaints', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_complaints_priority_level'), 'complaints', ['priority_level'], unique=False)
    op.create_index(op.f('ix_complaints_status'), 'complaints', ['status'], unique=False)
    op.create_index('ix_complaints_status_priority', 'complaints', ['status', 'priority_score'], unique=False)
    op.create_index(op.f('ix_complaints_user_id'), 'complaints', ['user_id'], unique=False)
    op.create_table('priority_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_priority_configs_is_active'), 'priority_configs', ['is_active'], unique=False)
    op.create_table('complaint_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('image_analysis_status', sa.String(length=20), nullable=False),
    sa.Column('detected_objects', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('image_severity_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_images_complaint_id'), 'complaint_images', ['complaint_id'], unique=False)
    op.create_table('complaint_similarities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('similar_complaint_id', sa.UUID(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['similar_complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_similarity_complaint', 'complaint_similarities', ['complaint_id'], unique=False)
    op.create_index('ix_similarity_pair', 'complaint_similarities', ['complaint_id', 'similar_complaint_id'], unique=True)
    op.create_index('ix_similarity_similar', 'complaint_similarities', ['similar_complaint_id'], unique=False)
    op.create_table('complaint_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('old_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_status_history_complaint_id'), 'complaint_status_history', ['complaint_id'], unique=False)
    op.create_table('prediction_audits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('prediction_type', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('prediction_source', sa.String(length=30), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=True),
    sa.Column('input_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('predicted_value', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('prediction_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('was_overridden', sa.Boolean(), nullable=False),
    sa.Column('overridden_by', sa.UUID(), nullable=True),
    sa.Column('override_value', sa.String(length=100), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('overridden_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_value', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['overridden_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_audits_complaint_id'), 'prediction_audits', ['complaint_id'], unique=False)
    op.create_table('priority_explanations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('factor', sa.String(length=50), nullable=False),
    sa.Column('contribution', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_priority_explanations_complaint_id'), 'priority_explanations', ['complaint_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_priority_explanations_complaint_id'), table_name='priority_explanations')
    op.drop_table('priority_explanations')
    op.drop_index(op.f('ix_prediction_audits_complaint_id'), table_name='prediction_audits')
    op.drop_table('prediction_audits')
    op.drop_index(op.f('ix_complaint_status_history_complaint_id'), table_name='complaint_status_history')
    op.drop_table('complaint_status_history')
    op.drop_index('ix_similarity_similar', table_name='complaint_similarities')
    op.drop_index('ix_similarity_pair', table_name='complaint_similarities')
    op.drop_index('ix_similarity_complaint', table_name='complaint_similarities')
    op.drop_table('complaint_similarities')
    op.drop_index(op.f('ix_complaint_images_complaint_id'), table_name='complaint_images')
    op.drop_table('complaint_images')
    op.drop_index(op.f('ix_priority_configs_is_active'), table_name='priority_configs')
    op.drop_table('priority_configs')
    op.drop_index(op.f('ix_complaints_user_id'), table_name='complaints')
    op.drop_index('ix_complaints_status_priority', table_name='complaints')
    op.drop_index(op.f('ix_complaints_status'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_priority_level'), table_name='complaints')
    op.drop_index('ix_complaints_location', table_name='complaints')
    op.drop_index(op.f('ix_complaints_incident_id'), table_name='complaints')
    op.drop_index('ix_complaints_department', table_name='complaints')
    op.drop_index('ix_complaints_created_at', table_name='complaints')
    op.drop_index(op.f('ix_complaints_complaint_number'), table_name='complaints')
    op.drop_index('ix_complaints_category', table_name='complaints')
    op.drop_table('complaints')
    op.drop_index('ix_users_role_active', table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_incidents_status_priority', table_name='incidents')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index('ix_incidents_location', table_name='incidents')
    op.drop_index('ix_incidents_category', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_category_department_mappings_department_id'), table_name='category_department_mappings')
    op.drop_index(op.f('ix_category_department_mappings_category_id'), table_name='category_department_mappings')
    op.drop_table('category_department_mappings')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
